### ISSUE TITLE
How to start the program

### ISSUE THREAD

**Issue by bernardo-rebelo** [milletyann/InstaCleanAndScrap#1]
Hi, 
I would like to know how you scraped for comments, I need a scraper to scrape a pool of posts from Instagram for my dataset.
I would appreciate the help!

**Comment by milletyann** [comment]
Hi Bernardo! I did not scrap the comments myself as it was given by my supervisor at the beginning of the project.
I will try to find the scraper and I'll keep you informed!

**Comment by milletyann** [comment]
I finally found the scraper my supervisor used initially, I pushed it in the "Initial scraper" folder but I didn't not test it, you may find it useful to some extent 🤞
